# Generated by Django 3.2 on 2021-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysdiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ImageField(default='', upload_to='%Y/%m/%d'),
        ),
    ]
